# Generated by Django 5.2.5 on 2025-08-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='developer_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github_url', models.URLField()),
                ('gist_link', models.CharField()),
                ('image', models.ImageField(upload_to='project_pics/')),
                ('developer', models.ManyToManyField(to='core.developer')),
            ],
        ),
    ]
