# Generated by Django 5.2.5 on 2025-08-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='alias',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='developer_pics/'),
        ),
    ]
